### PR TITLE
full CRUD code for restaurant - completed

### PR DESCRIPTION
**Pull request by jx0906**

### CODE REVIEW

**Review by natsumi-h — DISMISSED** [review]
Pending approval until error solved.

**Review by jx0906 — COMMENTED** [review]
tested to be working 
o/p from postman : {"restaurants":[]}

**Review by jx0906 — COMMENTED** [review]
validated latest edits to be working for GET all restaurants
output from postman:  
> {"restaurants":[]}

note: empty output because CREATE operation is not working yet

**Comment by natsumi-h** [comment]
test

**Review by jx0906 — COMMENTED** [review]
will disregard this as we clarified that i should have marked this PR as draft.

**Review by natsumi-h — APPROVED** [review]

**Comment by natsumi-h** [comment]
@jx0906 
Just quickly tried `GET` method and `CREATE` method and looks good to me!
Thank you for the dummy data generation as well.
Please go ahead to merge.

**Pull request merged**
